version: '3.8'

services:
  kalkylator:
    image: omaralhamad/bostadskalkyl:latest
    container_name: bostadskalkyl
    ports:
      - "3007:3000"
    volumes:
      - kalkylator_data:/app/data
      - kalkylator_public:/app/public
    restart: unless-stopped

volumes:
  kalkylator_data:
    external: true
  kalkylator_public:
    external: true