version: '3.8'

services:
  kalkylator:
    image: omaralhamad/bostadskalkyl:latest
    container_name: bostadskalkyl
    ports:
      - "3007:3000"
    volumes:
      - ./data:/app/data            # Loggfiler
      - ./public:/app/public        # HTML, JS, CSS mappning korrekt
    restart: unless-stopped